# Generated by Django 4.2.3 on 2023-07-09 09:45

from django.db import migrations, models
import movie_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128, validators=[movie_app.validators.check_len]),
        ),
    ]
